### ISSUE TITLE
Location Weather information

### ISSUE THREAD

**Issue by ve3elb** [JVital2013/vitality-goes#49]
Hello I am looking for help in setting this part up. Can anyone help me with the info needed to complete the setup. Thank you. 

RadarCode:
stateAbbr: ON
wxZone:
orig:
rwrOrig: 
city: Toronto
lat: 43.00
lon: -79.00
timezone: America/New_York

**Comment by JVital2013** [comment]
Only locations under the jurisdiction of the National Weather Service are supported, sorry. Canada is not.

Only some Canadian weather is supported, due to limited Canadian information in the EMWIN stream. Your best bet is to remove all the location information, other than timezone, to disable the current weather screen. Then, on the "other EMWIN" screen, set up a card like this to show Canadian UV information, which has some data on weather in Toronto:

![image](https://github.com/JVital2013/vitality-goes/assets/24253715/98710f5a-cead-45fb-8534-87f533d7df1b)
